export const PostActionTypes = {
  FETCH_POSTS: "FETCH_POSTS",
  SET_POSTS: "SET_POSTS",
  FETCH_POSTS_LOADING: "FETCH_POSTS_LOADING",
  ADD_POST: "ADD_POST",
  UPDATE_POST: "UPDATE_POST",
  MARK_COMPLETED: "MARK_COMPLETED",
  DELETE_POST: "DELETE_POST",
  BUTTON_LOADING: "BUTTON_LOADING",
};
